### ISSUE TITLE
Session not created: This version of ChromeDriver only supports Chrome version 85

### ISSUE THREAD

**Issue by dovy** [derek-baker/scraping-service#3]
Tried running your code directly and received this error. Any ideas?

```
[2021-12-29 04:54:07 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2021-12-29 04:54:07 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-12-29 04:54:07 +0000] [1] [INFO] Using worker: threads
[2021-12-29 04:54:07 +0000] [9] [INFO] Booting worker with pid: 9
[2021-12-29 04:54:08 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/app/main.py", line 19, in <module>
    browser = webdriver.Chrome(chrome_options=chrome_options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 85

[2021-12-29 04:54:08 +0000] [9] [INFO] Worker exiting (pid: 9)
[2021-12-29 04:54:08 +0000] [1] [INFO] Shutting down: Master
[2021-12-29 04:54:08 +0000] [1] [INFO] Reason: Worker failed to boot.[2021-12-29 04:54:07 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2021-12-29 04:54:07 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-12-29 04:54:07 +0000] [1] [INFO] Using worker: threads
[2021-12-29 04:54:07 +0000] [9] [INFO] Booting worker with pid: 9
[2021-12-29 04:54:08 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/app/main.py", line 19, in <module>
    browser = webdriver.Chrome(chrome_options=chrome_options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 85

[2021-12-29 04:54:08 +0000] [9] [INFO] Worker exiting (pid: 9)
[2021-12-29 04:54:08 +0000] [1] [INFO] Shutting down: Master
[2021-12-29 04:54:08 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by derek-baker** [comment]
I see the following error in the stack you posted: 'This version of ChromeDriver only supports Chrome version 85'

From the Readme: "You'll likely need to manually update the version of chromedriver-binary to latest"

**Comment by derek-baker** [comment]
Should be resolved by: https://github.com/derek-baker/scraping-service/pull/5
