### ISSUE TITLE
container fails to launch

### ISSUE THREAD

**Issue by dokato** [derek-baker/scraping-service#4]
The error I'm getting:
```
[2022-01-21 10:38:51 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2022-01-21 10:38:51 +0000] [1] [INFO] Using worker: threads
[2022-01-21 10:38:51 +0000] [11] [INFO] Booting worker with pid: 11
[2022-01-21 10:38:52 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/app/main.py", line 19, in <module>
    browser = webdriver.Chrome(chrome_options=chrome_options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 255

[2022-01-21 10:38:52 +0000] [11] [INFO] Worker exiting (pid: 11)
[2022-01-21 10:38:52 +0000] [1] [INFO] Shutting down: Master
[2022-01-21 10:38:52 +0000] [1] [INFO] Reason: Worker failed to boot.
```

I tried to update chromedriver binary to:
```
chromedriver-binary==v98.0.4758.48.0
```
but it didn't help.

**Comment by derek-baker** [comment]
I just merged the PR linked below, which may resolve your issue.

https://github.com/derek-baker/scraping-service/pull/5
